FROM node:{{ .node_version }}-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . .

# 🔒 Checkov standard: Never run as root!
RUN addgroup -S appgroup && adduser -S appuser -G appgroup && chown -R appuser /usr/src/app
USER appuser

EXPOSE {{ .app_port }}

# 🚀 Dynamic execution based on environment
CMD {{ .run_command }}
